sudo: required
dist: trusty
language: perl

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libdb-dev libxml2-dev libxslt1-dev texlive-latex-base

install:
 - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

script:
 - export PATH=`pwd`/perl5/bin:$PATH
 - export PERL5LIB=`pwd`/perl5/lib/perl5
 - export PERL_CPANM_OPT=--local-lib=`pwd`/perl5
 - cpanm https://github.com/KWARC/LaTeXML.git --notest
 - cpanm . -v
 - cd prototests/smglom
 - rm -f *.xml
 - make
 - cd ../cds
 - make

