sudo: required
dist: trusty
language: perl

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cpanminus texlive-latex-base

install:
 - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
 - cpanm App::cpanminus

script:
 - export PATH=`pwd`/perl5/bin:$PATH
 - cpanm https://github.com/KWARC/LaTeXML.git
 - cpanm .
 - cd prototests/smglom
 - rm -f *.xml
 - make
 - cd ../cds
 - make
